{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "photobooth-app.fullname" . }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "photobooth-app.fullname" . }}
  tls:
    insecureEdgeTerminationPolicy: None
    termination: edge
{{- end }}